### ISSUE TITLE
BVC firingrates go over max_fr

### ISSUE THREAD

**Issue by colleenjg** [RatInABox-Lab/RatInABox#110]
As mentioned in #108, BVC firing rates sometimes go over `max_fr`. I believe this is due to how `self.cell_fr_norm` is computed from locations uniformly sampled across the environment during initialization.

I've given it a lot of thought, and I don't think there's a straight forward perfect solution. However, I think I can propose a slight improvement. Increasing the resolution by making `dx` smaller is not ideal, as memory usage climbs quickly. So, I propose using the uniformly sampled locations, but also adding jittered locations. 

For clarity, I've separated the initialization from the init into its own function, but everything here is the same as before, except the lines in `if add_jittered:`. Basically, in addition to using the uniformly `locs` to estimate max firing, I also jitter each location with a value between `-dx/2` and `dx/2` in `x` and `y`. (Using `dx/2` should prevent any points going out of bounds.) These jittered locations are appended to `locs` and all of the values are used together to estimate max firing rate for each neuron. Importantly, this cannot make the estimates worse, as `locs` still includes the original uniformly sampled `locs`. It can only improve them in cases where the jittered locs find higher firing rates near the uniform locs. This does double the memory use, but my tests indicate it this is more than compensated for by the improvement in the estimates.

```
def _set_cell_fr_norm(self, dx=0.04, add_jittered=True):

    locs = self.Agent.Environment.discretise_environment(dx=dx)
    locs = locs.reshape(-1, locs.shape[-1])

    if add_jittered:
        jitter = np.random.uniform(-dx/2, dx/2, locs.shape)
        locs = np.append(locs, locs + jitter, axis=0)

    self.cell_fr_norm = np.ones(self.n) # value for initialization

    # ignores the warning raised during initialisation of the BVCs
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        _cell_fr_norm = np.max(self.get_state(evaluate_at=None, pos=locs), axis=1)
        self.cell_fr_norm = (_cell_fr_norm - self.min_fr) / (self.max_fr - self.min_fr)
```

From the examples below, you can see that **no jitter** and `dx=0.04` leads to 1.5% of firingrates in this random run I did being over the max firing rate of 1. Cutting `dx` in two greatly improves this (down to 0.6% of firingrates being above 1), but requires 4x more datapoints and in my tests using way too much memory. Using jitter and a higher `dx` (0.05) requires only a few more points and performs quite well (0.63% of firingrates above `max_fr`), though the max firingrate is higher than with `dx=0.02`. I've also included an example with `dx=0.04` and jitter for comparison purposes. Of course, this uses 2x more points than no jitter.

![jitter_effect](https://github.com/RatInABox-Lab/RatInABox/assets/26847334/96046569-8912-4937-a16d-a28ca73de697)

I've run it several times to make sure the improvement isn't a fluke. It might not be worth implementing this, as it's not an actual fix, but I figured I'd propose it just in case.

**A different solution would be a two-step estimate:** Use `locs` to identify the top 6 locations with the highest firingrates for each neuron, and then sample uniformly a certain number of points around those.

**Comment by colleenjg** [comment]
Here's another run 
![jitter_effect2](https://github.com/RatInABox-Lab/RatInABox/assets/26847334/6f1cb3bb-e3b0-4182-8233-d615edcf9998)

**Comment by TomGeorge1234** [comment]
It an interesting point. I agree there's no neat solution because there isn't a theoretical/analytic answer to whats the maximum firing rate of a BVC. It depends on the exact environment. 

I'm kind of happy with your solution. It depends how much you really mind that the `max_fr` overshoots the user desired value. I see a few options. 

Option 1: Do nothing and just tell in a comments that this is only an estimate.
Option 1.1: Your solution, add slightly jittered test points. Simple and easy but doesn't really fix it. 

Option 2: Redefine. If you _really_ minded a better way might be to keep it as it is and add a hard threshold. Some kind of tanh or threshold-linear function on the output of each neuron that just clips any overshoot back to `max_fr` (this works nicely because we can be sure its always an overshoot, not an undershoot. I don't particularly like this because the clipping could be quite bad for ego-BVCs (explained below). 

Option 3: We could redefine what `max_fr` means so that it can be calculated analytically. For example we could change it to mean "if the environment consisted of a single infinite straight wall what would the max firing rate of the cell be in this environment?". This could probably be computed analytically then used instead of the empirical estimate. Or what about this, if a cell had preferred distance range of X cm then wouldn't it _necessarily_ fire maximally in a the centre of a circular environment of radius X cm? This could be calculated and used as the scaling. Guaranteeably the cell must fire less or equal to this in its actual environment so it is a form of upper bound. As long as we tell the user this is what max_fr means they will get what they want.  
 
Note that it's going to be much worse for ego-centric BVCs where the (true) max_fr requires a grid search over positions _and_ head-directions which I think we're not currently implementing so the overshoot could be quite severe for ego-BVCs if II had to guess. Because of this, **whatever we choose** I'd advocate better explaining in the comments what max_fr means in the case of each vector cell as it's not such a trivial notion. 

Fwiw I think I'd lean option 1 or 1.1.

**Comment by colleenjg** [comment]
Thank you for the detailed response. I'm not sure what the best option is, but I realize that you are quite right! The head direction issue is probably contributing perhaps more than the sampling. This makes a lot of sense. I'm going to give this more thought to think of whether I can make a different small improvement that could substantially improve the estimate!

**Comment by TomGeorge1234** [comment]
Yeah but the head direction thing actually would only be an issue if you're using egocentric BVCs (`params = {'reference_frame':'egocentric'}` or you're using `FieldOfViewBVCs` etc.). Also I just test it and the overshoot isn't noticeably worse for ego-BVCs.

**Comment by colleenjg** [comment]
Ah, that makes sense, as that's where my student and I discovered the largest overshoot (`FieldOfViewBVCs`). Values up to `1.6` with `max_fr=1.0`.

**Comment by TomGeorge1234** [comment]
Ah ok, in which case your proposed fix wouldn't really solve their problem, we'll have to think of another way...

**Comment by TomGeorge1234** [comment]
Hi Colleen, where did we leave. What's the current workaround your student is using and do you think we should push ahead and implement something more proper?

**Comment by colleenjg** [comment]
Hey Tom, we are just setting a max on the firingrates for the particular downstream calculation we were performing. Sorry, haven't had time to look into this further, though it is on the to do list.

**Comment by TomGeorge1234** [comment]
Closing for now as current situation doesn't constitute a "bug" per se, but will happily reopen whenever needed...

**Comment by colleenjg** [comment]
Ok, dove back into this and figured out the analytical way of getting max_fr. It's quite simple:

```
self.cell_fr_norm = utils.von_mises(
    theta=self.test_angles.reshape(1, -1), 
    mu=0, 
    sigma=self.sigma_angles.reshape(-1, 1), 
    norm=1
).sum(axis=1)
```
That's it! It's basically just the von mises component of the calculation of `g` at line 1729. I skip the gaussian as we are interested in the max value of the normalized gaussian (i.e., 1). For the von mises, you don't need to pass tuning_angles to mu, because the test_angles fed into the cosine is hardcoded to cover 360 degrees (L1580) and so the mus will just rotate the angles unnecessarily (for our purposes here of obtaining a theoretical max). 

**Example relationship btw theoretical and estimated**
This graph shows an example of how using this method adjusts `self.cell_fr_norm` in one example. In my tests, the ratio of analytical to estimated cell_fr_norm didn't really go over 1.3ish max. I imagine though that if someone was using tuning distances that are unlikely to occur in the environment (e.g., bigger than the environment), then the currently estimated cell_fr_norm will have been very much undershooting the max.

![BVCs](https://github.com/user-attachments/assets/ba8a5875-11fd-4cd1-9a57-19d5fce3bf7a)

**Should generalize**
This should apply to all the different kinds of VectorCells, though I only tested with BoundaryVectorCells. With the BVCs I tried a bunch of parameter configurations just in case I'd missed something. In particular, I tried the egocentric frame of reference, which is what initially made me notice this issue. For `"diverging_manifold"`, it worked perfectly with the values I tested. `"uniform_manifold"` is the only case I tested where some of the theoretically calculated cell_fr_norm were just below the estimated ones (and thus some of the firingrates went just over the max firingrate). 

**Numerical error for small sigmas?**
I believe this was due to a numerical precision caused by small spatial resolution resulting in the fields having very small sigma_angle and sigma_distance values. I didn't try to nail down the exact parameters, but it disappeared for example when I increased the spatial resolution for uniform manifold to 0.06 (from default 0.02). If we do end up using the theoretical calculation for cell_fr_norm, we may want to consider clipping the firingrate for cleanliness. 

**Sandbox notebook**
I've also attached a little notebook to play around with vector cell parameters and visualize the relationship between the currently estimated `cell_fr_norm` and theoretically calculated one. Since I can't attach an ipynb, I've attached it as a handy PDF file...
[VCs_max_fr_issue.pdf](https://github.com/user-attachments/files/17874896/VCs_max_fr_issue.pdf)

Let me know what you think :)!

**Comment by TomGeorge1234** [comment]
Right, I think I understand. So to confirm, this is a way of numerically calculating the firing rate _as if_ the agent was in the centre of a perfect circle of walls all located at the distance_tuning (hence the sum over axis 1). In this case it's all circularly symmetric so you can arbitrarily set mu = 0 w.l.o.g. Seems good to me! 

Looking at your pdf it makes sense the _old_ estimate of max firing rate is lower than this new one is actually for a hypothetical perfectly-encircled-by-walls env which is an extreme case, likely not actually encountered in the real env. 

My only concern then is that the meaning of `max_fr` has subtly changed from "a rough estimate of the max fr in this current env (warning: could be a bit higher in reality)" to "max possible firing rate (reality will be a bit lower)". It's likely now that actual observed max BVCs firing rate will be lower than this analytical maximum which might confused users, perhaps not? I agree it comes with the benefit that you can now guarantee that it won't (ever) go above `max_fr` which is nice.  

Lastly I don't think this applies to other types of vector cells (e.g. OVCs). They don't even pre-calculate a `cell_fr_norm` in the `__init__` because the equation is by default normalised already for a single object, which I think is still the most reasonable way to do it. 


**Suggestions:** 
* Make the change, I think it's good!
* Update the docs slightly in BVC to explain this subtle redefinition of max_fr
* Maybe even put a link to this discussion in the docs. 

Thanks for digging back into this and nice solution!

**Comment by colleenjg** [comment]
Oh that's right! I had initially noted that this doesn't apply to objects or agents (since they are single points, right?), but then forgot.

I agree, that changing how `max_fr` is calculated could change things a bit for users. I think it nonetheless is a good thing for the reason you mentioned, and given the fact that the max firing rate was being surpassed by quite a bit for the FOV BVCs.

I agree with your suggestions. Will implement!

**Comment by colleenjg** [comment]
I'm not sure about the full circle analogy, since each BVC is only sensitive to a small area of space. I think the more correct conceptualization is that we are calculating the max activation as the activation if a boundary fully crossed each BVC's receptive field from one end to the other, via the center. Does that seem right?

**Comment by TomGeorge1234** [comment]
Hmmm. No, I do think the circle analogy is correct. Before the sum each term represent the response to a wall segment at `test_angle` for a cell with tuning `mu`. so then placing a wall segment at each test angle and summing `.sum(axis=1)` is analogous to a full circular wall. 

or do you still disagree? 

![bvc](https://github.com/user-attachments/assets/48306c1b-ecb9-44a3-bcfa-4f6df20f1341)

**Comment by colleenjg** [comment]
Oh right... yes because I set the Gaussian to 1 everywhere. So even though the receptive fields might in actuality taper off to zero quite quickly outside of their peak, they are computed across a complete circle. So for neurons with very high angle sigmas, the max activity computed will be much higher than what would ever be observed. 

It is definitionally consistent though, at least.

**Comment by TomGeorge1234** [comment]
yes you're right, its a good point, for sharply-angularly-tuned neurons the theoretical maximum is likely to be close to what is actually seen in the env. That's even better news!
